Repository sofastack/sofa-rpc-boot-projects, pull requests merged in 2019-09, with the labels that each got.

#200 fix remove service ,do not use consumerconfig as hashcode key
  sofa-boot-core/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/RpcBinding.java
Labels: bug, cla:yes, size/S

#201 change the rpc.all.version to 5.5.7
  sofa-boot-core/pom.xml
  sofa-boot-plugin/pom.xml
Labels: cla:yes, size/XS

#202 Prepare release 604
  .travis.yml
  pom.xml
  sofa-boot-core/pom.xml
  sofa-boot-plugin/pom.xml
  sofa-boot-samples/pom.xml
  sofa-boot-starter/pom.xml
  tools/change_version.sh
Labels: cla:yes, size/S, upgrade
